### ISSUE TITLE
Cyclic dependency error when referencing parent selector from child

### ISSUE THREAD

**Issue by kpatient** [pagestrip/reisy#9]
Steps to reproduce:

1. create an element with a child
2. reference the child from within the parent element reisy css
3. reference the parent from within the child reisy css

Note: this works if you remove the nested `$Child` reference in the parent component

Example:
```js
const buggedStyles = reisy`
@namespace Bug;

SomeComponent {
	position: fixed;

	& $Child {
		background: blue;
	}
}

Child {
	width: 100px;
	height: 100px;
	background: purple;

	/* SomeComponent is missing from output here */
	$SomeComponent:first-child & {
		outline: 3px solid red;
	}
}
`;

const SomeComponent = () => <div {...use(buggedStyles.SomeComponent)}>
	<div {...use(buggedStyles.Child)} />
</div>;
```

Error:
`Error: reisy: Node "Bug.SomeComponent" is part of a cyclic dependency.`

CSS Output:
```css
.pagestrip-root .Bug-Child {
  width: 100px;
  height: 100px;
  background: purple;
}
.pagestrip-root :first-child .Bug-Child {
  outline: 3px solid red;
}
.pagestrip-root .Bug-SomeComponent {
  position: fixed;
}
.pagestrip-root .Bug-SomeComponent .Bug-Child {
  background: blue;
}
```

**Comment by gimmixAT** [comment]
I tried to mitigate this a bit in https://github.com/pagestrip/reisy/commit/fcff7f23f92a8bc5b5e841d649fe6b1a90facdd0
This could still create some unexpected behaviors though since style might be sorted in an unexpected way.

The way it works now is to not generate a dependency if a reference is written before the self reference. e.g. `$Foo & { ... }` will create no dependency but `& $Foo { ... }` will.

This might have implications for more complex styles so this will need more testing.

**Comment by gimmixAT** [comment]
@kpatient  I released the changes as `1.6.0-rc1` under the `rc` tag so can test it easily by running `npm install reisy@rc`

**Comment by kpatient** [comment]
Another weird bug now happening:

Reisy:
```css
@namespace Navigation;
Navigation {
  $Kosk.Container > & {
	  & $NavRow:first-child {
  			background: red !important;
		  	$Media.medium {
			    padding: .5rem 1rem;
		  	}
	  }
  }
}
```

Output:
```css
@media only all and (min-width: 900px) {
  .pagestrip-root __rreq__4 > .Navigation-Navigation .Navigation-NavRow:first-child {
    padding: .5rem 1rem;
  }
}
```
